# permissions for end users to edit quarkushelmcharts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quarkushelmchart-editor-role
rules:
- apiGroups:
  - charts.wilda.fr
  resources:
  - quarkushelmcharts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.wilda.fr
  resources:
  - quarkushelmcharts/status
  verbs:
  - get
