# permissions for end users to edit quarkushelmcharts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: quarkushelmchart-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: helm-operator-samples
    app.kubernetes.io/part-of: helm-operator-samples
    app.kubernetes.io/managed-by: kustomize
  name: quarkushelmchart-editor-role
rules:
- apiGroups:
  - charts.wilda.fr
  resources:
  - quarkushelmcharts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.wilda.fr
  resources:
  - quarkushelmcharts/status
  verbs:
  - get
