# permissions for end users to view quarkushelmcharts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quarkushelmchart-viewer-role
rules:
- apiGroups:
  - charts.wilda.fr
  resources:
  - quarkushelmcharts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.wilda.fr
  resources:
  - quarkushelmcharts/status
  verbs:
  - get
